version: '3'

services:
  yumme:
    container_name: yumme
    build: .
    environment:
      DATABASE_HOST: mariadb
      CACHE_TYPE: redis
      REDIS_HOST: redis
    ports:
      - 8080:8080
    links:
      - mariadb
      - redis
    depends_on:
      - mariadb
      - redis

  mariadb:
    container_name: mariadb
    image: mariadb:10.6.7
    environment:
      - MYSQL_DATABASE=yumme
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:6.2.6
    volumes:
      - redis_data:/data

volumes:
  mariadb_data:
  redis_data:
