server:
    port: ${PORT:9000}
    servlet:
        context-path: /api/v1

spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:yumme}
        username: ${DATABASE_USERNAME:root}
        password: ${DATABASE_PASSWORD:root}

    aop:
        proxy-target-class: true

    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                ddl-auto: validate
    flyway:
        enabled: true
        sql-migration-prefix:
        baseline-on-migrate: true

    security:
        jwt:
            token:
                secret: secret-key
                expiration: 60
                realm: yumme

shiro:
    enabled: true
    web:
        enabled: true
