yumme:
  admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin}

  storage:
    directory: ${STORAGE_DIRECTORY:uploads/}

  security:
    pepper: ${PASSWORD_PEPPER:secret}
    realm: ${TOKEN_REALM:yumme}
    jwt:
      signing-key: ${JWT_SIGNING_KEY:secret}
      expiration-minutes: ${JWT_EXPIRATION_MINUTES:60}

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:yumme}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}

  aop:
    proxy-target-class: true

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: validate

  flyway:
    enabled: true
    sql-migration-prefix:
    baseline-on-migrate: true

  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB

shiro:
  enabled: true
  web:
    enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /spec
  swagger-ui:
    enabled: false
