server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:yumme}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}

  aop:
    proxy-target-class: true

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: validate

  flyway:
    enabled: true
    sql-migration-prefix:
    baseline-on-migrate: true

  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB

  main:
    # Used in OpenApiConfiguration.kt
    allow-bean-definition-overriding: true

shiro:
  enabled: true
  web:
    enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /spec
